name: cf
channels:
  - conda-forge
  - nodefaults
dependencies:
  - anaconda-client
  - python=3.10
  - requests
  - conda-smithy
  - pygithub
  - pydantic
  - cirun
  - conda-smithy >=3.30.1
  - conda-forge-metadata
